config/routes.rb
Rails.application.routes.draw do

  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tios
  resources :jovems
  resources :equipes
  resources :eventos
  resources :inicio
  
  devise_for :usuarios, path: 'admin', skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "inicio#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails.application.routes.draw do
  root 'application#hello'
end

app/models/equipe.rb
class Equipe < ApplicationRecord
    
    validates :ano, presence: {message: 'ano deve ser informado!'},
                           numericality: {message: 'deve conter sommente número!'}, #validates_numericality_of valida se foi digitado só número!
                           length: {maximum: 4, message: 'deve conter no máximo 4 números!'}
                           
    #length_of valida ou limita o tamanho ou a quantidade de caracteres informado no campo!
    validates_length_of :ano, minimum: 4, message: 'deve conter no mínimo 4 números!'
    
    validates :ano, presence: true, :numericality => {:greater_than => 0,  message: 'ano não pode ser zero ou negativo!' }
    
    validates :nome, presence: {message: 'nome deve ser informado!'},
                     length: {in: 5..100, message: 'deve conter entre 5 e 100 caracteres!'}
    
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :set_equipe, only: [:show, :edit, :update, :destroy]

  # GET /equipes
  # GET /equipes.json
  def index
    @equipes = Equipe.all
  end

  # GET /equipes/1
  # GET /equipes/1.json
  def show
  end

  # GET /equipes/new
  def new
    @equipe = Equipe.new
  end

  # GET /equipes/1/edit
  def edit
  end

  # POST /equipes
  # POST /equipes.json
  def create
    @equipe = Equipe.new(equipe_params)

    respond_to do |format|
      if @equipe.save
        format.html { redirect_to @equipe, notice: 'Equipe was successfully created.' }
        format.json { render :show, status: :created, location: @equipe }
      else
        format.html { render :new }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipes/1
  # PATCH/PUT /equipes/1.json
  def update
    respond_to do |format|
      if @equipe.update(equipe_params)
        format.html { redirect_to @equipe, notice: 'Equipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipe }
      else
        format.html { render :edit }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipes/1
  # DELETE /equipes/1.json
  def destroy
    @equipe.destroy
    respond_to do |format|
      format.html { redirect_to equipes_url, notice: 'Equipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipe
      @equipe = Equipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipe_params
      params.require(:equipe).permit(:ano, :nome, :observacoes)
    end
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/views/equipes/_form.html.erb
<%= form_for(equipe) do |f| %>
  <% if equipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipe.errors.count, "error") %> prohibited this equipe from being saved:</h2>

      <ul>
      <% equipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ano %>
    <%= f.number_field :ano %>
  </div>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :observacoes %>
    <%= f.text_field :observacoes %>
  </div>
  
  <div class="field">
    <%= f.label :integrantes %>
    <%= f.text_field :integrantes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipes/edit.html.erb
<h1>Editar Equipe</h1>

<%= render 'form', equipe: @equipe %>

<%= link_to 'Show', @equipe %> |
<%= link_to 'Back', equipes_path %>

app/views/equipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipes</h1>

<table>
  <thead>
    <tr>
      <th>Ano</th>
      <th>Nome</th>
      <th>Observacoes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipes.each do |equipe| %>
      <tr>
        <td><%= equipe.ano %></td>
        <td><%= equipe.nome %></td>
        <td><%= equipe.observacoes %></td>
        <td><%= link_to 'Mostrar', equipe %></td>
        <td><%= link_to 'Editar', edit_equipe_path(equipe) %></td>
        <td><%= link_to 'Excluir', equipe, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Equipe', new_equipe_path %>

app/views/equipes/index.pdf.erb
<h1>Equipes list report</h1>

<% @equipes.each do |articles| %>
  <p><%= articles %></p>
<% end %>

app/views/equipes/new.html.erb
<h1>Nova Equipe</h1>

<%= render 'Incluir nova equipe', equipe: @equipe %>

<%= link_to 'Voltar', equipes_path %>

app/views/equipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ano:</strong>
  <%= @equipe.ano %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @equipe.nome %>
</p>

<p>
  <strong>Observacoes:</strong>
  <%= @equipe.observacoes %>
</p>

<%= link_to 'Editar', edit_equipe_path(@equipe) %> |
<%= link_to 'Voltar', equipes_path %>