config/routes.rb
Rails.application.routes.draw do

  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tios
  resources :jovems
  resources :equipes
  resources :eventos
  resources :inicio
  
  devise_for :usuarios, path: 'admin', skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "inicio#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails.application.routes.draw do
  root 'application#hello'
end

app/models/jovem.rb
class Jovem < ApplicationRecord
    
    validates :nome, presence: {message: 'nome deve ser informado!'},
                     length: {in: 10..100, message: 'deve conter entre 10 e 100 caracteres!'}
    
    #presence_of torna o campo obrigatório!
    #validates_presence_of :data_nascimento
    #validates :data_nascimento, presence: true, :numericality => {:greater_than => 1950,  message: 'Ano de nascimento válido apartir de 1950!' }
    
    validates :ano_inicio, presence: {message: 'ano deve ser informado!'},
                           numericality: {message: 'deve conter sommente número!'}, #validates_numericality_of valida se foi digitado só número!
                           length: {maximum: 4, message: 'deve conter no máximo 4 números!'}
                           
   validates :ano_inicio, presence: true, :numericality => {:greater_than => 2000,  message: 'Ano válido apartir de 2000!' }
                           
    #length_of valida ou limita o tamanho ou a quantidade de caracteres informado no campo!
    validates_length_of :ano_inicio, minimum: 4, message: 'deve conter no mínimo 4 números!'
    
    #validates_length_of :endereco, in: 10..100, message: 'deve conter entre 10 e 100 caracteres!'
                     
    #validates_length_of :telefone, maximum: 10, message: 'deve conter no máximo 10 números!'
    #validates_length_of :telefone, minimum: 10, message: 'deve conter no mínimo 10 números!'
                    
   validates :celular, presence: {message: 'não pode ser deixado em branco!'},
                        numericality: {message: 'deve conter somente número!'},
                        length: {minimum: 11, message: 'deve conter no mínimo 11 números!'}
                        
    validates_length_of :celular, maximum: 11, message: 'deve conter no máximo 11 números!'
                         
    validates :email, presence: {message: 'não pode ser deixado em branco!'}, 
                      length: {minimum: 10, message: 'deve conter no mínimo 10 caracteres!'}, 
                      uniqueness: {message: 'email já cadastrado'} #Uniqueness não deixa criar dados duplicados no banco de dados!
    
    #validates_format_of Valida se o formato do objeto está correto
    validates_format_of :email,
                        :with => /\A[\w\._%-]+@[\w\.-]+\.[a-zA-Z]{2,4}\z/,
                        :if => Proc.new { |u| !u.email.nil? && !u.email.blank? },
                        :message => "Formato de email incorreto!"
                        
    #validates_length_of :observacao, in: 10..1000, message: 'deve conter entre 10 e 1000 caracteres!'
    
end

    #validacoes unidas em uma só https://www.devmedia.com.br/introducao-a-validacoes-com-ruby-on-rails/33926

    #validates :endereco, length: {in: 10..100, message: 'deve ter entre 10 e 100 caracteres'}

app/controllers/jovems_controller.rb
class JovemsController < ApplicationController
  before_action :set_jovem, only: [:show, :edit, :update, :destroy]

  # GET /jovems
  # GET /jovems.json
  def index
    @jovems = Jovem.all
  end

  # GET /jovems/1
  # GET /jovems/1.json
  def show
  end

  # GET /jovems/new
  def new
    @jovem = Jovem.new
  end

  # GET /jovems/1/edit
  def edit
  end

  # POST /jovems
  # POST /jovems.json
  def create
    @jovem = Jovem.new(jovem_params)

    respond_to do |format|
      if @jovem.save
        format.html { redirect_to @jovem, notice: 'Jovem was successfully created.' }
        format.json { render :show, status: :created, location: @jovem }
      else
        format.html { render :new }
        format.json { render json: @jovem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jovems/1
  # PATCH/PUT /jovems/1.json
  def update
    respond_to do |format|
      if @jovem.update(jovem_params)
        format.html { redirect_to @jovem, notice: 'Jovem was successfully updated.' }
        format.json { render :show, status: :ok, location: @jovem }
      else
        format.html { render :edit }
        format.json { render json: @jovem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jovems/1
  # DELETE /jovems/1.json
  def destroy
    @jovem.destroy
    respond_to do |format|
      format.html { redirect_to jovems_url, notice: 'Jovem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jovem
      @jovem = Jovem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jovem_params
      params.require(:jovem).permit(:nome, :data_nascimento, :ano_inicio, :endereco, :telefone, :celular, :email, :observacao)
    end
end

app/helpers/jovems_helper.rb
module JovemsHelper
end

app/views/jovems/_form.html.erb
<%= form_for(jovem) do |f| %>
  <% if jovem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jovem.errors.count, "error") %> prohibited this jovem from being saved:</h2>

      <ul>
      <% jovem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :data_nascimento %>
    <%= f.date_select :data_nascimento %>
  </div>

  <div class="field">
    <%= f.label :ano_inicio %>
    <%= f.number_field :ano_inicio %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_field :endereco %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :celular %>
    <%= f.text_field :celular %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :observacao %>
    <%= f.text_field :observacao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jovems/edit.html.erb
<h1>Editing Jovem</h1>

<%= render 'form', jovem: @jovem %>

<%= link_to 'Show', @jovem %> |
<%= link_to 'Back', jovems_path %>

app/views/jovems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jovems</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Ano inicio</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Observacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jovems.each do |jovem| %>
      <tr>
        <td><%= jovem.nome %></td>
        <td><%= jovem.data_nascimento %></td>
        <td><%= jovem.ano_inicio %></td>
        <td><%= jovem.endereco %></td>
        <td><%= jovem.telefone %></td>
        <td><%= jovem.celular %></td>
        <td><%= jovem.email %></td>
        <td><%= jovem.observacao %></td>
        <td><%= link_to 'Show', jovem %></td>
        <td><%= link_to 'Edit', edit_jovem_path(jovem) %></td>
        <td><%= link_to 'Destroy', jovem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jovem', new_jovem_path %>

app/views/jovems/new.html.erb
<h1>New Jovem</h1>

<%= render 'form', jovem: @jovem %>

<%= link_to 'Back', jovems_path %>

app/views/jovems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @jovem.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @jovem.data_nascimento %>
</p>

<p>
  <strong>Ano inicio:</strong>
  <%= @jovem.ano_inicio %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @jovem.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @jovem.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @jovem.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @jovem.email %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @jovem.observacao %>
</p>

<%= link_to 'Edit', edit_jovem_path(@jovem) %> |
<%= link_to 'Back', jovems_path %>