config/routes.rb
Rails.application.routes.draw do

  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tios
  resources :jovems
  resources :equipes
  resources :eventos
  resources :inicio
  
  devise_for :usuarios, path: 'admin', skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "inicio#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails.application.routes.draw do
  root 'application#hello'
end

app/models/evento.rb
class Evento < ApplicationRecord
    
    mount_uploader :foto, FotoUploader
    
    validates :titulo, presence: {message: 'nome do evennto deve ser informado!'},
                       length: {in: 5..100, message: 'deve conter entre 5 e 100 caracteres!'}
    
    #validates_presence_of :dta_evento, message: 'Data do evento deve ser informada!'
    
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:titulo, :dta_evento, :informacoes, :imagem)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(evento) do |f| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :dta_evento %>
    <%= f.date_select :dta_evento %>
  </div>

  <div class="field">
    <%= f.label :informacoes %>
    <%= f.text_field :informacoes %>
  </div>

  <div class="field">
    <%= f.label :imagem %>
    <%= f.text_field :imagem %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Dta evento</th>
      <th>Informacoes</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.titulo %></td>
        <td><%= evento.dta_evento %></td>
        <td><%= evento.informacoes %></td>
        <td><%= evento.imagem %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @evento.titulo %>
</p>

<p>
  <strong>Dta evento:</strong>
  <%= @evento.dta_evento %>
</p>

<p>
  <strong>Informacoes:</strong>
  <%= @evento.informacoes %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @evento.imagem %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>